language: node_js
node_js:
- '5'
env:
  global:
  - secure: oNyvFDQ+D4gS3R/l+k4eBSgSz3yWvW85eh47oC2EQYu5AAKhsM/eEJaUTVVNotnf7H8JRsoVjJarWGunK19aKRSk2D7bjJVRgQQ2cWc/1t0SPqI0JSTXEAWrzh8iGMKl4D0OdKzHDzizL5AGgwXs1qFqq1jySTThUsjkw8OHzgoQNfvxRUnrNF9douaF7BudTQv6g/uDn7AJzYa1fTzHmvAIPUMCIpVgY7k5ZTSzi3lwXmX5O/2sImj4bkjowQ/zhJXvY0oYyWVPtxYX9fiDUrIr93m5Lx85zqXHYqzmLSjfpoX43l/hCgXqzgP1IJygJkjsCv2Ox2RBO8vQGiVOYZ3RsjvFT81j90HDnGuSTK7LnIgDmro25FD0Beprz0xmbhwzfj6PkKwK0hrvY+arxrUYAo1vEdiB72ZKeUckUEXF50bOem1124m+wcK1moXIr7uZrtnIjYlAom9B5z31+OTI4xAcRRn3GpucigQ4CStYZ9d3UVNh2Si7yjvaLGkih7HoUGybc7oobdXzMREeUhQHzv0lvYSelPjqvjUN6fwiT5Q/wAjCezrT150okz+6Y8WFsKwLH7NgiodFx0XwYYPS6bZ0igAMbiZro+hfRAbIIB3xgJXcCwIsQPmlB482x7dvtECMcEEJw2L8hjRe+mNBsoSI9hLZIay2PlhBULw=
